#[derive(Debug)]
pub enum IrcErrorCode {
    ErrNoSuchNick = 401,
    ErrNoSuchServer = 402,
    ErrNoSuchChannel = 403,
    ErrCannotSendToChan = 404,
    ErrTooManyChannels = 405,
    ErrWasNoSuchNick = 406,
    ErrTooManyTargets = 407,
    ErrNoOrigin = 409,
    ErrNoRecipient = 411,
    ErrNoTextToSend = 412,
    ErrNoTopLevel = 413,
    ErrWildTopLevel = 414,
    ErrUnknownCommand = 421,
    ErrNoMotd = 422,
    ErrNoAdminInfo = 423,
    ErrFileError = 424,
    ErrNoNicknameGiven = 431,
    ErrErroneusNickname = 432,
    ErrNicknameInUse = 433,
    ErrNickCollision = 436,
    ErrUserNotInChannel = 441,
    ErrNotOnChannel = 442,
    ErrUserOnChannel = 443,
    ErrNoLogin = 444,
    ErrSummonDisabled = 445,
    ErrUsersDisabled = 446,
    ErrNotRegistered = 451,
    ErrNeedMoreParams = 461,
    ErrAlreadyRegistered = 462,
    ErrNoPermForHost = 463,
    ErrPasswdMismatch = 464,
    ErrYoureBannedCreep = 465,
    ErrKeySet = 467,
    ErrChannelIsFull = 471,
    ErrUnknownMode = 472,
    ErrInviteOnlyChan = 473,
    ErrBannedFromChan = 474,
    ErrBadChannelKey = 475,
    ErrNoPrivileges = 481,
    ErrChanOPrivsNeeded = 482,
    ErrCantKillServer = 483,
    ErrNoOperHost = 491,
    ErrUModeUnknownFlag = 501,
    ErrUsersDontMatch = 502,
}

impl IrcErrorCode {
    pub fn error_message(&self, target: &str) -> String {
        match self {
            IrcErrorCode::ErrNoSuchNick => format!("{} :No such nick/channel", target),
            IrcErrorCode::ErrNoSuchServer => format!("{} :No such server", target),
            IrcErrorCode::ErrNoSuchChannel => format!("{} :No such channel", target),
            IrcErrorCode::ErrCannotSendToChan => format!("{} :Cannot send to channel", target),
            IrcErrorCode::ErrTooManyChannels => {
                format!("{} :You have joined too many channels", target)
            }
            IrcErrorCode::ErrWasNoSuchNick => format!("{} :There was no such nickname", target),
            IrcErrorCode::ErrTooManyTargets => {
                format!("{} :Duplicate recipients. No message delivered", target)
            }
            IrcErrorCode::ErrNoOrigin => ":No origin specified".to_string(),
            IrcErrorCode::ErrNoRecipient => format!(":No recipient given ({})", target),
            IrcErrorCode::ErrNoTextToSend => ":No text to send".to_string(),
            IrcErrorCode::ErrNoTopLevel => format!("{} :No toplevel domain specified", target),
            IrcErrorCode::ErrWildTopLevel => format!("{} :Wildcard in toplevel domain", target),
            IrcErrorCode::ErrUnknownCommand => format!("{} :Unknown command", target),
            IrcErrorCode::ErrNoMotd => ":MOTD File is missing".to_string(),
            IrcErrorCode::ErrNoAdminInfo => format!("{} :No administrative info available", target),
            IrcErrorCode::ErrFileError => format!(":File error doing <file op> on {}", target),
            IrcErrorCode::ErrNoNicknameGiven => ":No nickname given".to_string(),
            IrcErrorCode::ErrErroneusNickname => format!("{} :Erroneous nickname", target),
            IrcErrorCode::ErrNicknameInUse => format!("{} :Nickname is already in use", target),
            IrcErrorCode::ErrNickCollision => format!("{} :Nickname collision KILL", target),
            IrcErrorCode::ErrUserNotInChannel => format!("{} :They aren't on that channel", target),
            IrcErrorCode::ErrNotOnChannel => format!("{} :You're not on that channel", target),
            IrcErrorCode::ErrUserOnChannel => format!("{} :is already on channel", target),
            IrcErrorCode::ErrNoLogin => format!("{} :User not logged in", target),
            IrcErrorCode::ErrSummonDisabled => ":SUMMON has been disabled".to_string(),
            IrcErrorCode::ErrUsersDisabled => ":USERS has been disabled".to_string(),
            IrcErrorCode::ErrNotRegistered => ":You have not registered".to_string(),
            IrcErrorCode::ErrNeedMoreParams => format!("{} :Not enough parameters", target),
            IrcErrorCode::ErrAlreadyRegistered => ":You may not reregister".to_string(),
            IrcErrorCode::ErrNoPermForHost => ":Your host isn't among the privileged".to_string(),
            IrcErrorCode::ErrPasswdMismatch => ":Password incorrect".to_string(),
            IrcErrorCode::ErrYoureBannedCreep => ":You are banned from this server".to_string(),
            IrcErrorCode::ErrKeySet => format!("{} :Channel key already set", target),
            IrcErrorCode::ErrChannelIsFull => format!("{} :Cannot join channel (+l)", target),
            IrcErrorCode::ErrUnknownMode => format!("{} :is unknown mode char to me", target),
            IrcErrorCode::ErrInviteOnlyChan => format!("{} :Cannot join channel (+i)", target),
            IrcErrorCode::ErrBannedFromChan => format!("{} :Cannot join channel (+b)", target),
            IrcErrorCode::ErrBadChannelKey => format!("{} :Cannot join channel (+k)", target),
            IrcErrorCode::ErrNoPrivileges => {
                ":Permission Denied- You're not an IRC operator".to_string()
            }
            IrcErrorCode::ErrChanOPrivsNeeded => format!("{} :You're not channel operator", target),
            IrcErrorCode::ErrCantKillServer => ":You cant kill a server!".to_string(),
            IrcErrorCode::ErrNoOperHost => ":No O-lines for your host".to_string(),
            IrcErrorCode::ErrUModeUnknownFlag => ":Unknown MODE flag".to_string(),
            IrcErrorCode::ErrUsersDontMatch => ":Can't change mode for other users".to_string(),
        }
    }
}
